---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 

inputs:
  - name: dp-census-alpha-api-proxy

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-census-alpha-api-proxy/ci/scripts/build.sh
